set(GODOTLIGHTER_VERSION_MAJOR 0 CACHE INTERNAL "")
set(GODOTLIGHTER_VERSION_MINOR 2 CACHE INTERNAL "")
set(GODOTLIGHTER_VERSION_PATCH 2 CACHE INTERNAL "")

set(GODOTLIGHTER_VERSION
	"${GODOTLIGHTER_VERSION_MAJOR}.${GODOTLIGHTER_VERSION_MINOR}.${GODOTLIGHTER_VERSION_PATCH}"
	CACHE INTERNAL "")

set(GODOTLIGHTER_GODOT_VERSION "4.3" CACHE INTERNAL "")

message(STATUS "GodotLighter Version: ${GODOTLIGHTER_VERSION}")

configure_file(
	"${CMAKE_SOURCE_DIR}/resources/godotlighter_version.h.in"
	"${GODOTLIGHTER_OUT}/godotlighter_version.h"
	@ONLY
)
